(** Generated by scripts/generate-rocq-init.py from coupon.wat.
    Source SHA256: 7a9f27123d328af28c6012dc5ca97899b6d6a1de3ce2dfb5060220600cede336
    Binary SHA256: 160ac9d31d0d824018ac39728e1674f69ee92e02edc5e4da2446382b2f509ac2
    Regenerate with make rocq-init. *)
From Stdlib Require Import Strings.Byte List.
From Wasm Require Import datatypes binary_format_parser.
Import ListNotations.

Definition coupon_binary : list Byte.byte := [
  x00; x61; x73; x6d; x01; x00; x00; x00; x01; x24; x06; x60; x02; x6f; x6f; x01;
  x6f; x60; x02; x6f; x6f; x01; x7f; x60; x01; x6f; x01; x7f; x60; x01; x6f; x01;
  x6f; x60; x02; x6f; x7f; x01; x6f; x60; x03; x7f; x6f; x6f; x01; x6f; x02; xb7;
  x04; x15; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x08; x69; x73; x5f; x65;
  x71; x75; x61; x6c; x00; x01; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x11;
  x69; x73; x5f; x73; x74; x6f; x72; x61; x67; x65; x5f; x63; x6f; x75; x70; x6f;
  x6e; x00; x02; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x0f; x69; x73; x5f;
  x66; x6f; x72; x63; x65; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x02; x08; x66;
  x69; x78; x70; x6f; x69; x6e; x74; x0c; x69; x73; x5f; x65; x71; x5f; x63; x6f;
  x75; x70; x6f; x6e; x00; x02; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x0e;
  x69; x73; x5f; x65; x76; x61; x6c; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x02;
  x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x0f; x69; x73; x5f; x61; x70; x70;
  x6c; x79; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x02; x08; x66; x69; x78; x70;
  x6f; x69; x6e; x74; x0f; x69; x73; x5f; x74; x68; x69; x6e; x6b; x5f; x63; x6f;
  x75; x70; x6f; x6e; x00; x02; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x18;
  x63; x72; x65; x61; x74; x65; x5f; x61; x70; x70; x6c; x69; x63; x61; x74; x69;
  x6f; x6e; x5f; x74; x68; x75; x6e; x6b; x00; x03; x08; x66; x69; x78; x70; x6f;
  x69; x6e; x74; x14; x63; x72; x65; x61; x74; x65; x5f; x73; x74; x72; x69; x63;
  x74; x5f; x65; x6e; x63; x6f; x64; x65; x00; x03; x08; x66; x69; x78; x70; x6f;
  x69; x6e; x74; x15; x63; x72; x65; x61; x74; x65; x5f; x73; x68; x61; x6c; x6c;
  x6f; x77; x5f; x65; x6e; x63; x6f; x64; x65; x00; x03; x08; x66; x69; x78; x70;
  x6f; x69; x6e; x74; x0e; x67; x65; x74; x5f; x63; x6f; x75; x70; x6f; x6e; x5f;
  x6c; x68; x73; x00; x03; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x0e; x67;
  x65; x74; x5f; x63; x6f; x75; x70; x6f; x6e; x5f; x72; x68; x73; x00; x03; x08;
  x66; x69; x78; x70; x6f; x69; x6e; x74; x10; x63; x72; x65; x61; x74; x65; x5f;
  x65; x71; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x00; x08; x66; x69; x78; x70;
  x6f; x69; x6e; x74; x12; x63; x72; x65; x61; x74; x65; x5f; x65; x76; x61; x6c;
  x5f; x63; x6f; x75; x70; x6f; x6e; x00; x00; x08; x66; x69; x78; x70; x6f; x69;
  x6e; x74; x13; x63; x72; x65; x61; x74; x65; x5f; x74; x68; x69; x6e; x6b; x5f;
  x63; x6f; x75; x70; x6f; x6e; x00; x00; x08; x66; x69; x78; x70; x6f; x69; x6e;
  x74; x13; x63; x72; x65; x61; x74; x65; x5f; x66; x6f; x72; x63; x65; x5f; x63;
  x6f; x75; x70; x6f; x6e; x00; x00; x08; x66; x69; x78; x70; x6f; x69; x6e; x74;
  x0d; x67; x65; x74; x5f; x74; x72; x65; x65; x5f; x73; x69; x7a; x65; x00; x02;
  x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x0d; x67; x65; x74; x5f; x74; x72;
  x65; x65; x5f; x64; x61; x74; x61; x00; x04; x08; x66; x69; x78; x70; x6f; x69;
  x6e; x74; x0b; x69; x73; x5f; x62; x6c; x6f; x62; x5f; x6f; x62; x6a; x00; x02;
  x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x07; x69; x73; x5f; x64; x61; x74;
  x61; x00; x02; x08; x66; x69; x78; x70; x6f; x69; x6e; x74; x09; x69; x73; x5f;
  x6f; x62; x6a; x65; x63; x74; x00; x02; x03; x0f; x0e; x00; x00; x00; x00; x00;
  x00; x00; x00; x00; x00; x00; x00; x00; x05; x04; x08; x02; x6f; x00; x00; x70;
  x01; x0d; x0d; x07; xed; x02; x0f; x13; x6d; x61; x6b; x65; x5f; x65; x71; x5f;
  x74; x72; x65; x65; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x15; x15; x6d; x61;
  x6b; x65; x5f; x65; x76; x61; x6c; x5f; x74; x72; x65; x65; x5f; x63; x6f; x75;
  x70; x6f; x6e; x00; x16; x1b; x6d; x61; x6b; x65; x5f; x66; x6f; x72; x63; x65;
  x5f; x72; x65; x73; x75; x6c; x74; x5f; x65; x71; x5f; x63; x6f; x75; x70; x6f;
  x6e; x00; x17; x13; x6d; x61; x6b; x65; x5f; x65; x76; x61; x6c; x5f; x65; x71;
  x5f; x63; x6f; x75; x70; x6f; x6e; x00; x18; x1d; x6d; x61; x6b; x65; x5f; x74;
  x68; x69; x6e; x6b; x5f; x61; x70; x70; x6c; x69; x63; x61; x74; x69; x6f; x6e;
  x5f; x63; x6f; x75; x70; x6f; x6e; x00; x19; x1a; x6d; x61; x6b; x65; x5f; x74;
  x68; x69; x6e; x6b; x5f; x74; x6f; x5f; x66; x6f; x72; x63; x65; x5f; x63; x6f;
  x75; x70; x6f; x6e; x00; x1a; x22; x6d; x61; x6b; x65; x5f; x66; x6f; x72; x63;
  x65; x5f; x74; x6f; x5f; x65; x6e; x63; x6f; x64; x65; x5f; x73; x74; x72; x69;
  x63; x74; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x1b; x18; x6d; x61; x6b; x65;
  x5f; x65; x76; x61; x6c; x5f; x62; x6c; x6f; x62; x6f; x62; x6a; x5f; x63; x6f;
  x75; x70; x6f; x6e; x00; x1c; x1a; x6d; x61; x6b; x65; x5f; x65; x71; x5f; x61;
  x70; x70; x6c; x69; x63; x61; x74; x69; x6f; x6e; x5f; x63; x6f; x75; x70; x6f;
  x6e; x00; x1d; x1c; x6d; x61; x6b; x65; x5f; x65; x71; x5f; x65; x6e; x63; x6f;
  x64; x65; x5f; x73; x74; x72; x69; x63; x74; x5f; x63; x6f; x75; x70; x6f; x6e;
  x00; x1e; x0f; x6d; x61; x6b; x65; x5f; x73; x79; x6d; x5f; x63; x6f; x75; x70;
  x6f; x6e; x00; x1f; x11; x6d; x61; x6b; x65; x5f; x74; x72; x61; x6e; x73; x5f;
  x63; x6f; x75; x70; x6f; x6e; x00; x20; x10; x6d; x61; x6b; x65; x5f; x73; x65;
  x6c; x66; x5f; x63; x6f; x75; x70; x6f; x6e; x00; x21; x0b; x6d; x61; x6b; x65;
  x5f; x63; x6f; x75; x70; x6f; x6e; x00; x22; x07; x63; x6f; x75; x70; x6f; x6e;
  x73; x01; x00; x09; x15; x01; x02; x01; x41; x00; x0b; x00; x0d; x15; x1d; x17;
  x1e; x19; x1a; x1b; x18; x1c; x16; x1f; x20; x21; x0a; xfd; x07; x0e; x92; x01;
  x02; x01; x6f; x02; x7f; xfc; x10; x00; x21; x03; x41; x00; x21; x04; x02; x40;
  x03; x40; x20; x04; x20; x03; x4e; x0d; x01; x20; x04; x25; x00; x10; x03; x04;
  x40; x01; x05; x00; x0b; x20; x04; x41; x01; x6a; x21; x04; x0c; x00; x0b; x0b;
  x20; x00; x10; x10; x20; x03; x46; x04; x6f; x20; x01; x10; x10; x20; x03; x46;
  x04; x6f; x41; x00; x21; x04; x02; x40; x03; x40; x20; x04; x20; x03; x4e; x0d;
  x01; x20; x04; x25; x00; x21; x02; x20; x00; x20; x04; x10; x11; x20; x02; x10;
  x0a; x10; x00; x04; x40; x20; x01; x20; x04; x10; x11; x20; x02; x10; x0b; x10;
  x00; x04; x40; x01; x05; x00; x0b; x05; x00; x0b; x20; x04; x41; x01; x6a; x21;
  x04; x0c; x00; x0b; x0b; x20; x00; x20; x01; x10; x0c; x05; x00; x0b; x05; x00;
  x0b; x0b; x92; x01; x02; x01; x6f; x02; x7f; xfc; x10; x00; x21; x03; x41; x00;
  x21; x04; x02; x40; x03; x40; x20; x04; x20; x03; x4e; x0d; x01; x20; x04; x25;
  x00; x10; x04; x04; x40; x01; x05; x00; x0b; x20; x04; x41; x01; x6a; x21; x04;
  x0c; x00; x0b; x0b; x20; x00; x10; x10; x20; x03; x46; x04; x6f; x20; x01; x10;
  x10; x20; x03; x46; x04; x6f; x41; x00; x21; x04; x02; x40; x03; x40; x20; x04;
  x20; x03; x4e; x0d; x01; x20; x04; x25; x00; x21; x02; x20; x00; x20; x04; x10;
  x11; x20; x02; x10; x0a; x10; x00; x04; x40; x20; x01; x20; x04; x10; x11; x20;
  x02; x10; x0b; x10; x00; x04; x40; x01; x05; x00; x0b; x05; x00; x0b; x20; x04;
  x41; x01; x6a; x21; x04; x0c; x00; x0b; x0b; x20; x00; x20; x01; x10; x0d; x05;
  x00; x0b; x05; x00; x0b; x0b; x6f; x01; x03; x6f; x41; x00; x25; x00; x21; x02;
  x41; x01; x25; x00; x21; x03; x41; x02; x25; x00; x21; x04; x20; x02; x10; x02;
  x04; x6f; x20; x03; x10; x02; x04; x6f; x20; x04; x10; x03; x04; x6f; x20; x02;
  x10; x0b; x20; x04; x10; x0a; x10; x00; x04; x6f; x20; x03; x10; x0b; x20; x04;
  x10; x0b; x10; x00; x04; x6f; x20; x02; x10; x0a; x20; x00; x10; x00; x04; x6f;
  x20; x03; x10; x0a; x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0c;
  x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x05;
  x00; x0b; x05; x00; x0b; x0b; x51; x01; x02; x6f; x41; x00; x25; x00; x21; x02;
  x41; x01; x25; x00; x21; x03; x20; x02; x10; x04; x04; x6f; x20; x03; x10; x03;
  x04; x6f; x20; x02; x10; x0a; x20; x03; x10; x0a; x10; x00; x04; x6f; x20; x03;
  x10; x0b; x20; x00; x10; x00; x04; x6f; x20; x02; x10; x0b; x20; x01; x10; x00;
  x04; x6f; x20; x00; x20; x01; x10; x0d; x05; x00; x0b; x05; x00; x0b; x05; x00;
  x0b; x05; x00; x0b; x05; x00; x0b; x0b; x53; x01; x02; x6f; x41; x00; x25; x00;
  x21; x02; x41; x01; x25; x00; x21; x03; x20; x02; x10; x04; x04; x6f; x20; x03;
  x10; x05; x04; x6f; x20; x02; x10; x0b; x20; x03; x10; x0a; x10; x00; x04; x6f;
  x20; x02; x10; x0a; x10; x07; x20; x00; x10; x00; x04; x6f; x20; x03; x10; x0b;
  x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0e; x05; x00; x0b; x05;
  x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x3e; x01; x01; x6f;
  x41; x00; x25; x00; x21; x02; x20; x02; x10; x06; x04; x6f; x20; x02; x10; x0b;
  x10; x13; x04; x6f; x20; x02; x10; x0a; x20; x00; x10; x00; x04; x6f; x20; x02;
  x10; x0b; x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0f; x05; x00;
  x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x40; x01; x01; x6f; x41;
  x00; x25; x00; x21; x02; x20; x02; x10; x02; x04; x6f; x20; x02; x10; x0b; x10;
  x14; x04; x6f; x20; x02; x10; x0b; x20; x01; x10; x00; x04; x6f; x20; x02; x10;
  x0a; x10; x08; x20; x00; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0c; x05;
  x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x1c; x00; x20; x00;
  x10; x12; x04; x6f; x20; x00; x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01;
  x10; x0d; x05; x00; x0b; x05; x00; x0b; x0b; x37; x01; x01; x6f; x41; x00; x25;
  x00; x21; x02; x20; x02; x10; x03; x04; x6f; x20; x00; x20; x02; x10; x0a; x10;
  x07; x10; x00; x04; x6f; x20; x01; x20; x02; x10; x0b; x10; x07; x10; x00; x04;
  x6f; x20; x00; x20; x01; x10; x0c; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b;
  x0b; x37; x01; x01; x6f; x41; x00; x25; x00; x21; x02; x20; x02; x10; x03; x04;
  x6f; x20; x02; x10; x0a; x10; x08; x20; x00; x10; x00; x04; x6f; x20; x02; x10;
  x0b; x10; x08; x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0c; x05;
  x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x33; x01; x01; x6f; x41; x00; x25;
  x00; x21; x02; x20; x02; x10; x03; x04; x6f; x20; x02; x10; x0b; x20; x00; x10;
  x00; x04; x6f; x20; x02; x10; x0a; x20; x01; x10; x00; x04; x6f; x20; x00; x20;
  x01; x10; x0c; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x51; x01; x02;
  x6f; x41; x00; x25; x00; x21; x02; x41; x01; x25; x00; x21; x03; x20; x02; x10;
  x03; x04; x6f; x20; x03; x10; x03; x04; x6f; x20; x02; x10; x0b; x20; x03; x10;
  x0a; x10; x00; x04; x6f; x20; x00; x20; x02; x10; x0a; x10; x00; x04; x6f; x20;
  x01; x20; x03; x10; x0b; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0c; x05;
  x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x05; x00; x0b; x0b; x13;
  x00; x20; x00; x20; x01; x10; x00; x04; x6f; x20; x00; x20; x01; x10; x0c; x05;
  x00; x0b; x0b; x16; x00; x20; x00; xfc; x10; x01; x49; x04; x6f; x20; x01; x20;
  x02; x20; x00; x11; x00; x01; x05; x00; x0b; x0b
].

(** Compute the actual module AST. Parsing failure is a compilation error,
    rather than a default module or an assumption about the input. *)
Definition coupon_module : module.
Proof.
  let parsed := eval vm_compute in (run_parse_module coupon_binary) in
  lazymatch parsed with
  | Some ?m => exact m
  | None => fail "WasmCert-Coq could not parse coupon.wat"
  end.
Defined.

Lemma coupon_module_parsed : run_parse_module coupon_binary = Some coupon_module.
Proof. vm_compute; reflexivity. Qed.
