#!/usr/bin/env python3
"""Generate the WasmCert-Coq module used by the coupon execution proofs."""

import argparse
import hashlib
from pathlib import Path
import subprocess
import tempfile


def generate(source: Path) -> str:
    # coupon.wat contains module fields; WABT requires an enclosing module.
    with tempfile.TemporaryDirectory(prefix="fix-proof-rocq-") as temp:
        wat = Path(temp) / "coupon.wat"
        binary = Path(temp) / "coupon.wasm"
        wat.write_bytes(b"(module\n" + source.read_bytes() + b"\n)\n")
        subprocess.run(["wat2wasm", str(wat), "-o", str(binary)], check=True)
        data = binary.read_bytes()
    rows = ["  " + "; ".join(f"x{b:02x}" for b in data[i:i + 16])
            for i in range(0, len(data), 16)]
    byte_list = ";\n".join(rows)
    source_digest = hashlib.sha256(source.read_bytes()).hexdigest()
    binary_digest = hashlib.sha256(data).hexdigest()
    return f"""(** Generated by scripts/generate-rocq-init.py from coupon.wat.
    Source SHA256: {source_digest}
    Binary SHA256: {binary_digest}
    Regenerate with make rocq-init. *)
From Stdlib Require Import Strings.Byte List.
From Wasm Require Import datatypes binary_format_parser.
Import ListNotations.

Definition coupon_binary : list Byte.byte := [
{byte_list}
].

(** Compute the actual module AST. Parsing failure is a compilation error,
    rather than a default module or an assumption about the input. *)
Definition coupon_module : module.
Proof.
  let parsed := eval vm_compute in (run_parse_module coupon_binary) in
  lazymatch parsed with
  | Some ?m => exact m
  | None => fail "WasmCert-Coq could not parse coupon.wat"
  end.
Defined.

Lemma coupon_module_parsed : run_parse_module coupon_binary = Some coupon_module.
Proof. vm_compute; reflexivity. Qed.
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="reject a stale generated module")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    output = root / "wasm-proofs" / "rocq" / "Init.v"
    generated = generate(root / "coupon.wat")
    if args.check:
        if not output.exists() or output.read_text() != generated:
            parser.exit(1, "Init.v is stale; run make rocq-init\n")
    else:
        if not output.exists() or output.read_text() != generated:
            output.write_text(generated)


if __name__ == "__main__":
    main()
